### ISSUE TITLE
 OAuth2Auth authentication provider, proxy support

### ISSUE THREAD

**Issue by nevenr** [eclipse-vertx/vertx-auth#103]
### Version

* vert.x core: 3.3.3
* vert.x auth: 3.3.3

### Context

If app need proxy to reach oauth2 authorization site "Internal Server Error" is thrown:

```
Nov 17, 2016 9:18:24 PM io.vertx.ext.web.impl.RoutingContextImplBase
SEVERE: Unexpected exception in route
io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection timed out: no further information: some.site.com/1.2.3.4:443
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:347)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:340)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:627)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:551)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:465)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:437)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873)
	at java.lang.Thread.run(Thread.java:745)
```

in step while browser trying to get oauth callback  http://localhost:8080/callback?code=xyz123&redirect_uri=%2Fprotected%2Fsomepage&state=

### Reproducer
```
OAuth2ClientOptions config = new OAuth2ClientOptions()
		.setClientID("ClientID")
		.setClientSecret("ClientSecret")
		.setSite("https://some.site.com")
		.setAuthorizationPath("/oauth/authorize")
		.setTokenPath("/oauth/token");
config.setProxyOptions(new ProxyOptions());


OAuth2Auth authProvider = OAuth2Auth.create(vertx, OAuth2FlowType.AUTH_CODE, config);
OAuth2AuthHandler oauth2 = OAuth2AuthHandler.create(authProvider, "http://localhost:8080");

oauth2.setupCallback(router.get("/callback"));
router.route("/protected/*").handler(oauth2);

```	

Possible cause is that in https://github.com/vert-x3/vertx-auth/blob/3.3.3/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2API.java#L114 OAuth2ClientOptions are not consulted.

Regards,
N.

**Comment by pmlopes** [comment]
This issue has been addressed on master:

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-oauth2/src/main/java/io/vertx/ext/auth/oauth2/impl/OAuth2API.java#L114
