### ISSUE TITLE
OAuth2 AccessToken response scope's value is null causing NPE

### ISSUE THREAD

**Issue by leotu** [eclipse-vertx/vertx-auth#189]
### Version

* vert.x core: 3.5.1
* vert.x auth: 3.5.1

### Context

~~~java
JsonObject tokenConfig = new JsonObject() //
				.put("code", code) //
				.put("redirect_uri", "...");

		oauth2.authenticate(tokenConfig, res -> {
			if (res.failed()) {
				log.error("", res.cause()); // error, the code provided is not valid
			} else {
				// Get the access token object (the authorization code is given from the previous step).
				User token = res.result();
				log.debug("token: {}", token.principal());
			}
		});
~~~

show error

~~~ava
java.lang.NullPointerException: null
	at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.init(OAuth2TokenImpl.java:132)
	at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.<init>(OAuth2TokenImpl.java:83)
	at io.vertx.ext.auth.oauth2.impl.flow.AuthCodeImpl.lambda$0(AuthCodeImpl.java:81)
	at io.vertx.ext.auth.oauth2.impl.flow.AbstractOAuth2Flow.lambda$0(AbstractOAuth2Flow.java:135)
	at io.vertx.ext.auth.oauth2.impl.OAuth2API.lambda$2(OAuth2API.java:121)
	at io.vertx.core.http.impl.HttpClientResponseImpl$BodyHandler.notifyHandler(HttpClientResponseImpl.java:302)
	at io.vertx.core.http.impl.HttpClientResponseImpl.lambda$0(HttpClientResponseImpl.java:192)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:256)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.endResponse(Http1xClientConnection.java:376)
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:456)
	at io.vertx.core.http.impl.Http1xClientHandler.handleMessage(Http1xClientHandler.java:115)
	at io.vertx.core.http.impl.Http1xClientHandler.handleMessage(Http1xClientHandler.java:1)
	at io.vertx.core.net.impl.VertxHandler.lambda$4(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:745)
~~~

### Do you have a reproducer?

* JUnit test code
~~~java
package io.vertx.spi.ext.oauth2;

import java.util.Collections;
import java.util.HashSet;
import java.util.Set;
import java.util.regex.Pattern;

import org.junit.Test;

import io.vertx.core.json.JsonObject;

/**
 * https://tools.ietf.org/html/draft-ietf-oauth-v2-31#page-32
 */
public class OAuth2AccessTokenScopeTest {

	// private final String accessToken; // REQUIRED
	// private final String tokenType; // REQUIRED
	// private Integer expiresIn; // RECOMMENDED, seconds
	// private String refreshToken; // OPTIONAL
	// private String scope; // OPTIONAL

	protected final Set<String> cachedPermissions = new HashSet<>();

	/**
	 * @see io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl#init
	 */
	@Test
	public void createAccessTokenScope() {
		String tokenStr = "{\"token_type\":\"bearer\",\"scope\":null,\"expires_in\":3600,\"access_token\":\"eyJhbGciOiJub25lIn0.eyJzdWIiOiIxQTJCM0M0fjUhNiQ3WDhZOVowIn0.\",\"refresh_token\":null}";

		/**
		 * The RAW token
		 */
		JsonObject token = new JsonObject(tokenStr);

		// attempt to decode tokens
		// if (provider != null) {
		// accessToken = decodeToken(token.getString("access_token"));
		// refreshToken = decodeToken(token.getString("refresh_token"));
		// idToken = decodeToken(token.getString("id_token"));

		// the permission cache needs to be clear
		// clearCache();
		// rebuild cache
		// if (token.containsKey("scope")) {
		// Collections.addAll(cachedPermissions,
		// token.getString("scope", "").split(Pattern.quote(provider.getScopeSeparator())));
		// }
		// }

		if (token.containsKey("scope")) {
			Collections.addAll(cachedPermissions, token.getString("scope", "").split(Pattern.quote(getScopeSeparator())));
		}

	}

	/**
	 * @see io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl#getScopeSeparator
	 */
	public String getScopeSeparator() {
		// final String sep = config.getScopeSeparator();
		// return sep == null ? " " : sep;
		return " ";
	}
}
~~~

### Steps to reproduce

1. Method: 
io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl#init

~~~java
 private void init() {
    if (token.containsKey("expires_in")) {
      Long expiresIn;
      try {
        expiresIn = token.getLong("expires_in");
      } catch (ClassCastException e) {
        // for some reason someone decided to send a number as a String...
        expiresIn = Long.valueOf(token.getString("expires_in"));
      }
      token.put("expires_at", System.currentTimeMillis() + 1000 * expiresIn);
    }

    // attempt to decode tokens
    if (provider != null) {
      accessToken = decodeToken(token.getString("access_token"));
      refreshToken = decodeToken(token.getString("refresh_token"));
      idToken = decodeToken(token.getString("id_token"));

      // the permission cache needs to be clear
      clearCache();
      // rebuild cache
      if (token.containsKey("scope")) {
        Collections.addAll(cachedPermissions, token.getString("scope", "").split(Pattern.quote(provider.getScopeSeparator())));
      }
    }
  }
~~~

2.  When scope's value is null
ex:
~~~java
		String tokenStr = "{\"token_type\":\"bearer\",\"scope\":null,\"expires_in\":3600,\"access_token\":\"eyJhbGciOiJub25lIn0.eyJzdWIiOiIxQTJCM0M0fjUhNiQ3WDhZOVowIn0.\",\"refresh_token\":null}";

		/**
		 * The RAW token
		 */
		JsonObject token = new JsonObject(tokenStr);
~~~

3. NPE at
~~~java
if (token.containsKey("scope")) {
   ...
   token.getString("scope", "").split(...)  <== here
   ...
}
~~~

token.getString("scope", "") will return null not "",  raising NPE

**Comment by pmlopes** [comment]
explicit scope as "null" is not common but possible ;) this has been fixed on master
