### ISSUE TITLE
Suppress error stack of JWT trying to load unsupported MAC

### ISSUE THREAD

**Issue by panjiesw** [eclipse-vertx/vertx-auth#19]
Hi,

Currently, as `JWT` class is trying to load MAC algorithm of configured keystore file, it logs NullPointerException if an algorithm isn't supported, as shown in [this](https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWT.java#L55) line. This makes the application logs to be polluted with rather meaningless error stack trace like so

```
22:49:23.968 [vert.x-eventloop-thread-2] io.vertx.ext.auth.jwt.impl.JWT [WARN ] [API] - HS256 not supported
java.lang.NullPointerException: null
    at io.vertx.ext.auth.jwt.impl.JWT.getMac(JWT.java:86) ~[vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at io.vertx.ext.auth.jwt.impl.JWT.<init>(JWT.java:53) ~[vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.<init>(JWTAuthProviderImpl.java:77) [vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at io.vertx.ext.auth.jwt.JWTAuth.create(JWTAuth.java:39) [vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at com.panjiesw.std.api.ApiVerticle.createAuthProvider(ApiVerticle.java:115) [main/:na]
    at com.panjiesw.std.api.ApiVerticle.startModule(ApiVerticle.java:88) [main/:na]
    at com.panjiesw.std.api.ApiVerticle.lambda$handleService$1(ApiVerticle.java:78) [main/:na]
    at com.panjiesw.std.api.ApiVerticle$$Lambda$8/383266732.handle(Unknown Source) [main/:na]
    at io.vertx.core.impl.DeploymentManager.lambda$reportResult$159(DeploymentManager.java:436) [vertx-core-3.0.0-milestone6.jar:na]
    at io.vertx.core.impl.DeploymentManager$$Lambda$14/677334899.handle(Unknown Source) [vertx-core-3.0.0-milestone6.jar:na]
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:312) [vertx-core-3.0.0-milestone6.jar:na]
    at io.vertx.core.impl.ContextImpl$$Lambda$7/1448061896.run(Unknown Source) [vertx-core-3.0.0-milestone6.jar:na]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.25.Final.jar:4.0.25.Final]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
22:49:23.969 [vert.x-eventloop-thread-2] io.vertx.ext.auth.jwt.impl.JWT [WARN ] [API] - HS384 not supported
java.lang.NullPointerException: null
    at io.vertx.ext.auth.jwt.impl.JWT.getMac(JWT.java:86) ~[vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at io.vertx.ext.auth.jwt.impl.JWT.<init>(JWT.java:53) ~[vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.<init>(JWTAuthProviderImpl.java:77) [vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at io.vertx.ext.auth.jwt.JWTAuth.create(JWTAuth.java:39) [vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at com.panjiesw.std.api.ApiVerticle.createAuthProvider(ApiVerticle.java:115) [main/:na]
    at com.panjiesw.std.api.ApiVerticle.startModule(ApiVerticle.java:88) [main/:na]
    at com.panjiesw.std.api.ApiVerticle.lambda$handleService$1(ApiVerticle.java:78) [main/:na]
    at com.panjiesw.std.api.ApiVerticle$$Lambda$8/383266732.handle(Unknown Source) [main/:na]
    at io.vertx.core.impl.DeploymentManager.lambda$reportResult$159(DeploymentManager.java:436) [vertx-core-3.0.0-milestone6.jar:na]
    at io.vertx.core.impl.DeploymentManager$$Lambda$14/677334899.handle(Unknown Source) [vertx-core-3.0.0-milestone6.jar:na]
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:312) [vertx-core-3.0.0-milestone6.jar:na]
    at io.vertx.core.impl.ContextImpl$$Lambda$7/1448061896.run(Unknown Source) [vertx-core-3.0.0-milestone6.jar:na]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.25.Final.jar:4.0.25.Final]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
22:49:23.971 [vert.x-eventloop-thread-2] io.vertx.ext.auth.jwt.impl.JWT [WARN ] [API] - HS512 not supported
java.lang.NullPointerException: null
    at io.vertx.ext.auth.jwt.impl.JWT.getMac(JWT.java:86) ~[vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at io.vertx.ext.auth.jwt.impl.JWT.<init>(JWT.java:53) ~[vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.<init>(JWTAuthProviderImpl.java:77) [vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at io.vertx.ext.auth.jwt.JWTAuth.create(JWTAuth.java:39) [vertx-auth-jwt-3.0.0-milestone6.jar:na]
    at com.panjiesw.std.api.ApiVerticle.createAuthProvider(ApiVerticle.java:115) [main/:na]
    at com.panjiesw.std.api.ApiVerticle.startModule(ApiVerticle.java:88) [main/:na]
    at com.panjiesw.std.api.ApiVerticle.lambda$handleService$1(ApiVerticle.java:78) [main/:na]
    at com.panjiesw.std.api.ApiVerticle$$Lambda$8/383266732.handle(Unknown Source) [main/:na]
    at io.vertx.core.impl.DeploymentManager.lambda$reportResult$159(DeploymentManager.java:436) [vertx-core-3.0.0-milestone6.jar:na]
    at io.vertx.core.impl.DeploymentManager$$Lambda$14/677334899.handle(Unknown Source) [vertx-core-3.0.0-milestone6.jar:na]
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:312) [vertx-core-3.0.0-milestone6.jar:na]
    at io.vertx.core.impl.ContextImpl$$Lambda$7/1448061896.run(Unknown Source) [vertx-core-3.0.0-milestone6.jar:na]
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:380) [netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357) [netty-all-4.0.25.Final.jar:4.0.25.Final]
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:116) [netty-all-4.0.25.Final.jar:4.0.25.Final]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_45]
```

The log should not include the error stack trace i think, like in SIGNATURE loops [below that line](https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWT.java#L64)

**Comment by pmlopes** [comment]
In #20 the fix will not throw a NPE, instead it will log as a lower level INFO that the algorithm is  not present in the store. The choosen level is INFO due to the fact that JWT claims that all algorithms are optional.

**Comment by borov333** [comment]
Is there a way to completely turn off the output, even at the INFO level? I think developer shall have full control what messages are printed.

**Comment by pmlopes** [comment]
It's a logger so you can always define the allowed output level.

**Comment by MyTotoro** [comment]
This logger shouldn't be configured to accomplish this change, I believe `io.vertx.ext.auth.jwt.impl.JWT` should have a toggle which would output this.

logger level INFO is too common to be changed just to reduce this output
