### ISSUE TITLE
Shiro Auth prints exception on stderr when user is invalid

### ISSUE THREAD

**Issue by FroMage** [eclipse-vertx/vertx-auth#203]
### Version

* vert.x core: 3.5.1
* vert.x auth: 3.5.1

### Context

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-shiro/src/main/java/io/vertx/ext/auth/shiro/impl/ShiroAuthProviderImpl.java#L79 shows that an invalid user will throw an exception, which is caught by the blocking-runner thread, and handled properly, but logged on stderr with a big stack trace that leads me to think it was not handled. We should not log the exception, or not throw.

**Comment by pmlopes** [comment]
I'm confused the code pointer is about throwing an exception. It doesn't print it, do you have a stack trace so I can see where it gets printed?

**Comment by FroMage** [comment]
Here's the stack trace I get:

```
io.vertx.core.VertxException: org.apache.shiro.authc.UnknownAccountException: Realm [org.apache.shiro.realm.text.PropertiesRealm@68b4b234] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - stef, rememberMe=false].
	at io.vertx.ext.auth.shiro.impl.ShiroAuthProviderImpl.lambda$authenticate$0(ShiroAuthProviderImpl.java:79)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$1(ContextImpl.java:273)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.shiro.authc.UnknownAccountException: Realm [org.apache.shiro.realm.text.PropertiesRealm@68b4b234] was unable to find account data for the submitted AuthenticationToken [org.apache.shiro.authc.UsernamePasswordToken - stef, rememberMe=false].
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doSingleRealmAuthentication(ModularRealmAuthenticator.java:184)
	at org.apache.shiro.authc.pam.ModularRealmAuthenticator.doAuthenticate(ModularRealmAuthenticator.java:267)
	at org.apache.shiro.authc.AbstractAuthenticator.authenticate(AbstractAuthenticator.java:198)
	at org.apache.shiro.mgt.AuthenticatingSecurityManager.authenticate(AuthenticatingSecurityManager.java:106)
	at org.apache.shiro.mgt.DefaultSecurityManager.login(DefaultSecurityManager.java:270)
	at org.apache.shiro.subject.support.DelegatingSubject.login(DelegatingSubject.java:256)
	at io.vertx.ext.auth.shiro.impl.ShiroAuthProviderImpl.lambda$authenticate$0(ShiroAuthProviderImpl.java:77)
	... 6 more
```

**Comment by FroMage** [comment]
OK, you're right, I'm an idiot, I am the one printing the exception. So sorry about the time waste :(
