### ISSUE TITLE
refresh token is hanging

### ISSUE THREAD

**Issue by micjaesc** [eclipse-vertx/vertx-auth#211]
### Version

* vert.x core 3.5.1:
* vert.x auth 3.5.1:

### Context

when calling refresh token,  there is no any  results on callback. In other words, callback is never called (with success or failure) and it hangs forever. Even  if I have some problems with token provider, i should get callback with error.

Below our usage in Kotlin
```
    private fun refreshToken(accessToken: AccessToken?, environment: SpidEnvironment): Future<String> {
        var future = Future.future<String>()
        accessToken!!.refresh { ar ->
            if (ar.succeeded()) {
                println("Token refreshed")
                future.complete(accessToken.principal()?.getString("access_token"))
            } else {
                println("Problem with refreshing token: " + ar.cause().message)
                future = createNewToken(vertx, environment)
            }
        }
        return future
    }
```
### Do you have a reproducer?

no

### Extra

On my production I can only see stacktrace 
```
java.lang.RuntimeException: Not enough or too many segments
	at io.vertx.ext.jwt.JWT.decode(JWT.java:259) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.decodeToken(OAuth2TokenImpl.java:102) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.init(OAuth2TokenImpl.java:124) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.<init>(OAuth2TokenImpl.java:83) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.ext.auth.oauth2.impl.flow.ClientImpl.lambda$getToken$0(ClientImpl.java:53) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.ext.auth.oauth2.impl.flow.AbstractOAuth2Flow.lambda$getToken$0(AbstractOAuth2Flow.java:135) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.ext.auth.oauth2.impl.OAuth2API.lambda$null$1(OAuth2API.java:121) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.HttpClientResponseImpl$BodyHandler.notifyHandler(HttpClientResponseImpl.java:302) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.HttpClientResponseImpl.lambda$bodyHandler$0(HttpClientResponseImpl.java:192) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:256) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.endResponse(Http1xClientConnection.java:376) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:456) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.Http1xClientHandler.handleMessage(Http1xClientHandler.java:115) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.http.impl.Http1xClientHandler.handleMessage(Http1xClientHandler.java:32) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337) ~[subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195) [subscription-api-jar-with-dependencies.jar:?]
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:144) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1380) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1159) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1194) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:141) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886) [subscription-api-jar-with-dependencies.jar:?]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [subscription-api-jar-with-dependencies.jar:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_162]
```

**Comment by micjaesc** [comment]
> problem was located in different area. Please ignore ticket
