### ISSUE TITLE
OAuth2AuthHandler not failing for invalid JWT

### ISSUE THREAD

**Issue by Jotschi** [eclipse-vertx/vertx-auth#216]
### Version

* vert.x core: 3.5.1
* vert.x auth: 3.5.1

### Context

The OAuth2TokenImpl is just returning null when a token can't be decoded. I would expect that the `OAuth2AuthProviderImpl.decodeToken()` method catches the exception and fails using the provided handlers.

```
java.lang.RuntimeException: Not enough or too many segments
	at io.vertx.ext.jwt.JWT.decode(JWT.java:259) ~[vertx-jwt-3.5.1.jar:3.5.1]
	at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.decodeToken(OAuth2TokenImpl.java:102) [vertx-auth-oauth2-3.5.1.jar:3.5.1]
	at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.init(OAuth2TokenImpl.java:124) [vertx-auth-oauth2-3.5.1.jar:3.5.1]
	at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.<init>(OAuth2TokenImpl.java:83) [vertx-auth-oauth2-3.5.1.jar:3.5.1]
	at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.decodeToken(OAuth2AuthProviderImpl.java:211) [vertx-auth-oauth2-3.5.1.jar:3.5.1]
	at io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl.lambda$parseCredentials$1(OAuth2AuthHandlerImpl.java:119) [vertx-web-3.5.1.jar:3.5.1]
	at io.vertx.ext.web.handler.impl.AuthorizationAuthHandler.parseAuthorization(AuthorizationAuthHandler.java:97) ~[vertx-web-3.5.1.jar:3.5.1]
	at io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl.parseCredentials(OAuth2AuthHandlerImpl.java:101) [vertx-web-3.5.1.jar:3.5.1]
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:129) ~[vertx-web-3.5.1.jar:3.5.1]
	at io.vertx.ext.web.handler.impl.AuthHandlerImpl.handle(AuthHandlerImpl.java:39) ~[vertx-web-3.5.1.jar:3.5.1]
```
### Steps to reproduce

1. Setup OAuth2 handlers and invoke request using:
```Authorization: Bearer borked```

2. Observe that the OAuth2 handler is not failing and a empty user is set to the context.

**Comment by MightyEagle82** [comment]
I've faced with this issue too.
I think the root is in **decodeToken** method of **OAuth2TokenImpl** class. The method is called from the constructor and it consumes an exception rather than throws/rethrows it.
```
} catch (RuntimeException e) {
    LOG.warn("Cannot decode token:", e);
}
```
If an exception would be thrown then **OAuth2AuthHandlerImpl** could respond with 401 HTTP code as designed (see **parseCredentials** method).
```
((OAuth2Auth) authProvider).decodeToken(token, decodeToken -> {
    if (decodeToken.failed()) {
        handler.handle(Future.failedFuture(new HttpStatusException(401, decodeToken.cause().getMessage())));
        return;
    }
    ...
}
```
Please fix the issue as soon as possible because of it is a severe security issue.

**Comment by pmlopes** [comment]
@Jotschi @artyomsafronov I've a PR that fixes this bug, for the moment, please assert that the user in the session is not empty and return a 401 in that case. Once a release is available with this fix then the workaround is not necessary. Sorry for the inconvenience.
