### ISSUE TITLE
OAuth2AuthHandlerImpl#opaqueAccessToken() throws ClassCastException

### ISSUE THREAD

**Issue by rraumberger** [eclipse-vertx/vertx-auth#249]
### Version

* vertx-auth-oauth2: 3.5.3, 3.5.4

### Context

After upgrading to vertx-auth-oauth2 3.5.4 (from 3.5.2) the below snippet started to fail.
We use a more sophisticated version, but the essential parts are

    OAuth2AuthHandlerImpl.parseCredentials(routingContext, res -> {
                AccessToken accessToken = (AccessToken) routingContext.user();
                // Some authentication code needing the opaqueAccessToken
                accessToken.opaqueAccessToken();
                routingContext.next();
            });
    }

After a quick analysis, I can say that `OAuth2TokenImpl#opaqueAccessToken` throws a `ClassCastException` since the upgrade.

Relevant part of the stacktrace:
> java.lang.ClassCastException: io.vertx.core.json.JsonObject cannot be cast to java.lang.CharSequence
	at io.vertx.core.json.JsonObject.getString(JsonObject.java:111)
	at io.vertx.ext.auth.oauth2.impl.OAuth2TokenImpl.opaqueAccessToken(OAuth2TokenImpl.java:162)
	at lambda from above snippet
	at io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl.lambda$null$0(OAuth2AuthHandlerImpl.java:127)
	at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.decodeToken(OAuth2AuthProviderImpl.java:218)
	at io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl.lambda$parseCredentials$1(OAuth2AuthHandlerImpl.java:119)
	at io.vertx.ext.web.handler.impl.AuthorizationAuthHandler.parseAuthorization(AuthorizationAuthHandler.java:97)
	at io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl.parseCredentials(OAuth2AuthHandlerImpl.java:101)

### Extra

* This issue also occurs in 3.5.3

**Comment by pmlopes** [comment]
@rraumberger could you check if the current master still suffers from this? There has been a huge refactoring to the oauth code and we're about to start the 3.6 release cycle.

**Comment by rraumberger** [comment]
@pmlopes this issue is not reproducible with the current 3.6.0-SNAPSHOT version and it works as expected.
