### ISSUE TITLE
Exception handler in OAuth2API is called multiple times

### ISSUE THREAD

**Issue by bauchpinsel** [eclipse-vertx/vertx-auth#250]
### Version

* vert.x core: 3.5.4
* vert.x auth: 3.5.4

### Context

The exception handler at io.vertx.ext.auth.oauth2.impl.OAuth2API:108 is maybe called multiple times, resulting in a variety of errors. This happens for example when the verticle is being shutdown while the process of authentication is ongoing. The client.close() in line 110 is causing "Client already closed", because the client was closed due to the shutdown, thus resulting into an additional exception.

Maybe this is more of an issue for the core team? I wrote similar code to the one in OAuth2API an struggled with the same problem myself as well.

```
java.lang.IllegalStateException: Client is closed
	at io.vertx.core.http.impl.HttpClientImpl.checkClosed(HttpClientImpl.java:1035)
	at io.vertx.core.http.impl.HttpClientImpl.close(HttpClientImpl.java:901)
	at io.vertx.ext.auth.oauth2.impl.OAuth2API.lambda$null$0(OAuth2API.java:110)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleException(HttpClientResponseImpl.java:266)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:255)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.endResponse(Http1xClientConnection.java:424)
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:507)
	at io.vertx.core.http.impl.Http1xClientHandler.handleMessage(Http1xClientHandler.java:119)
	at io.vertx.core.http.impl.Http1xClientHandler.handleMessage(Http1xClientHandler.java:33)
	at io.vertx.core.net.impl.VertxHandler.lambda$channelRead$1(VertxHandler.java:146)
	at io.vertx.core.impl.ContextImpl.lambda$wrapTask$2(ContextImpl.java:337)
	at io.vertx.core.impl.ContextImpl.executeFromIO(ContextImpl.java:195)

```

or

`java.lang.IllegalStateException: Result is already complete: succeeded`

**Comment by pmlopes** [comment]
Please re-open if still relevant
