### ISSUE TITLE
Creating a new JWT token and adding user to session results in exceptions deserializing the JWT user object later

### ISSUE THREAD

**Issue by apatrida** [eclipse-vertx/vertx-auth#26]
When clustered using Hazelcast, create JWT Token, validate it by calling provider.authenticate() then routingContext.setUser() so it is available immediately.  Next requests that come in all fail with:

```
19:19:56.440 [vert.x-eventloop-thread-2] ERROR i.v.e.w.impl.RoutingContextImplBase - Unexpected exception in route
com.hazelcast.nio.serialization.HazelcastSerializationException: Problem while reading DataSerializable, namespace: 0, id: 0, class: 'io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap$DataSerializableHolder', exception: Failed to load class io.vertx.core.VertxException: java.lang.InstantiationException: io.vertx.ext.auth.jwt.impl.JWTUser
    at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:120) ~[hazelcast-3.5.jar:3.5]
    at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:39) ~[hazelcast-3.5.jar:3.5]
    at com.hazelcast.nio.serialization.StreamSerializerAdapter.read(StreamSerializerAdapter.java:41) ~[hazelcast-3.5.jar:3.5]
    at com.hazelcast.nio.serialization.SerializationServiceImpl.toObject(SerializationServiceImpl.java:276) ~[hazelcast-3.5.jar:3.5]
    at com.hazelcast.spi.impl.NodeEngineImpl.toObject(NodeEngineImpl.java:200) ~[hazelcast-3.5.jar:3.5]
    at com.hazelcast.map.impl.MapServiceContextImpl.toObject(MapServiceContextImpl.java:281) ~[hazelcast-3.5.jar:3.5]
    at com.hazelcast.map.impl.proxy.MapProxySupport.toObject(MapProxySupport.java:1114) ~[hazelcast-3.5.jar:3.5]
    at com.hazelcast.map.impl.proxy.MapProxyImpl.get(MapProxyImpl.java:82) ~[hazelcast-3.5.jar:3.5]
    at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap.lambda$get$13(HazelcastAsyncMap.java:46) ~[vertx-hazelcast-3.0.0.jar:na]
    at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap$$Lambda$72/589483425.handle(Unknown Source) ~[na:na]
    at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$14(ContextImpl.java:279) ~[vertx-core-3.0.0.jar:na]
    at io.vertx.core.impl.ContextImpl$$Lambda$35/1335061928.run(Unknown Source) ~[na:na]
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor.lambda$new$161(OrderedExecutorFactory.java:91) ~[vertx-core-3.0.0.jar:na]
    at io.vertx.core.impl.OrderedExecutorFactory$OrderedExecutor$$Lambda$34/711310213.run(Unknown Source) ~[na:na]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_25]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_25]
    at java.lang.Thread.run(Thread.java:745) [na:1.8.0_25]
Caused by: java.lang.IllegalStateException: Failed to load class io.vertx.core.VertxException: java.lang.InstantiationException: io.vertx.ext.auth.jwt.impl.JWTUser
    at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap$DataSerializableHolder.readData(HazelcastAsyncMap.java:178) ~[vertx-hazelcast-3.0.0.jar:na]
    at com.hazelcast.nio.serialization.DataSerializer.read(DataSerializer.java:111) ~[hazelcast-3.5.jar:3.5]
    ... 16 common frames omitted
Caused by: io.vertx.core.VertxException: io.vertx.core.VertxException: java.lang.InstantiationException: io.vertx.ext.auth.jwt.impl.JWTUser
    at io.vertx.ext.web.sstore.impl.SessionImpl.readDataFromBuffer(SessionImpl.java:309) ~[vertx-web-3.0.0.jar:na]
    at io.vertx.ext.web.sstore.impl.SessionImpl.readFromBuffer(SessionImpl.java:145) ~[vertx-web-3.0.0.jar:na]
    at io.vertx.spi.cluster.hazelcast.impl.HazelcastAsyncMap$DataSerializableHolder.readData(HazelcastAsyncMap.java:176) ~[vertx-hazelcast-3.0.0.jar:na]
    ... 17 common frames omitted
Caused by: io.vertx.core.VertxException: java.lang.InstantiationException: io.vertx.ext.auth.jwt.impl.JWTUser
    at io.vertx.ext.web.handler.impl.UserHolder.readFromBuffer(UserHolder.java:79) ~[vertx-web-3.0.0.jar:na]
    at io.vertx.ext.web.sstore.impl.SessionImpl.readDataFromBuffer(SessionImpl.java:299) ~[vertx-web-3.0.0.jar:na]
    ... 19 common frames omitted
Caused by: java.lang.InstantiationException: io.vertx.ext.auth.jwt.impl.JWTUser
    at java.lang.Class.newInstance(Class.java:423) ~[na:1.8.0_25]
    at io.vertx.ext.web.handler.impl.UserHolder.readFromBuffer(UserHolder.java:75) ~[vertx-web-3.0.0.jar:na]
    ... 20 common frames omitted
Caused by: java.lang.NoSuchMethodException: io.vertx.ext.auth.jwt.impl.JWTUser.<init>()
    at java.lang.Class.getConstructor0(Class.java:3074) ~[na:1.8.0_25]
    at java.lang.Class.newInstance(Class.java:408) ~[na:1.8.0_25]
    ... 21 common frames omitted
```

That last "caused by" seems to say that something wants it to have a default constructor and it does not?

**Comment by apatrida** [comment]
@pmlopes @purplefox this is BLOCKING for use of JWT in a clustered environment and only a 1-line fix for a default constructor (but please check all vert-x modules that might have objects that go into cluster store and be sure they work with hazelcast clustering)

**Comment by pmlopes** [comment]
I see that the default constructor can cause issues, but i don't understand why would you want to save the JWT user on the session? The whole point of using JWT is that you don't need sessions, JWTUser objects are not supposed to be serialized since the data can always be reconstructed from the token itself and there are never issues with synchronization or cache. 

However i made a PR to avoid crashing if someone really wants to serialize the user over hazelcast

**Comment by apatrida** [comment]
@pmlopes well, let's say that maybe the person that wants this was @pmlopes, because it is your code that does just that.  You wrote code at this line https://github.com/vert-x3/vertx-web/blob/c9d2a05e708d167b6f8dcc65ac3baf26899fba48/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java#L123 that stores the user into the context, which basically causes it to be serialized into Hazelcast if you have a clustered session manager configured.   Or maybe it is the UserSessionHandler being on the route that does that, but same net effect.

So yes, thanks for the PR it is needed because using JWT with a clustered session causes it to blow up.

**Comment by apatrida** [comment]
And yes, we use JWT and a few other auth types at the same time on sometimes the same routes, so its quite fun.  And the JWT is in the session for web based calls, and some REST calls coming from web based clients, but for pure REST API calls is only the JWT.  Real world, odd stuff happens, but you can see above that `context.setUser(...)` allows it to happen (we do the same in our code, because we don't use the JWTAuthHandler but our own).  Either way, thanks for the PR, hope it comes through to a release soon.

**Comment by purplefox** [comment]
I don't really understand this. As Paulo says JWT is meant to avoid sessions, so I can't understand the use case for storing it in a clustered session.

**Comment by apatrida** [comment]
@purplefox When you set the user into the context, internally that puts it into the session.  It isn't our choice, it is how Vert.x is currently working using the JWTAuthHandlerImpl.   And then it blows up if clustered.  Therefore using JWT with Hazelcast clustering does NOT work currently.  

So it is the relationship between `routingContext.user()` and `routingContext.setUser(newJwt)` that isn't working.  So you guys keep mentioning that the use case isn't understood, yet YOU coded the use case and there isn't a way to update the `routingContext.user()` object without it going into hazelcast and blowing up.  So how do we update this in the `routingContext` safely?  And are you going to fix the code linked above that also causes this failure within your own handler?

**Comment by apatrida** [comment]
And can we get a small release to fix this object, I'm stuck without clustering because of this one silly thing.

**Comment by apatrida** [comment]
from: https://github.com/vert-x3/vertx-web/blob/c9d2a05e708d167b6f8dcc65ac3baf26899fba48/src/main/java/io/vertx/ext/web/handler/impl/JWTAuthHandlerImpl.java#L123

```
authProvider.authenticate(authInfo, res -> {
        if (res.succeeded()) {
          final User user2 = res.result();
          context.setUser(user2);  // CAUSES HAZELCAST EXCEPTION!!!!
          authorise(user2, context);
        } else {
          log.warn("JWT decode failure");
          context.fail(401);
        }
      });
```

so what do we do?  avoid clustering until 3.1.0?  custom builds?  Just need a 3.0.0.1 vertx-auth-jwt with the fix from commit https://github.com/vert-x3/vertx-auth/commit/1c5ad96d15e5a8f62fe2602d43f76c34ed565cc7

**Comment by apatrida** [comment]
The logging message:

```
public JWTUser() {
    // required if the object is serialized, however this is not a good idea
    // because JWT are supposed to be used in stateless environments
    log.info("You are probably serializing the JWT User, JWT are supposed to be used in stateless servers!");
 }
```

in the commit above will confuse people who see it when vertx3-web `JWTAuthHandlerImpl` causes this to happen without them knowing it.  They'll have thousands of these log entries for something they didn't do.  @pmlopes

**Comment by apatrida** [comment]
anyway, I copied the code into my own tree with updated fixes, works fine.  I must be the only clustered session w/JWT enabled user for vertx3.
