### ISSUE TITLE
"vertx-auth-shiro-js/shiro_auth" will crash if you included "vertx-web-js/router" before it and authenticate successfully

### ISSUE THREAD

**Issue by skomorokh** [eclipse-vertx/vertx-auth#29]
For some reason the order of inclusion of Vert.x JS components matters: putting the router before shiro auth causes this error on the 3.0.0 release upon successful authentication: 

```
Unhandled exception 
vertx-js/util/utils.js:208 TypeError: undefined is not an Object
        at jdk.nashorn.internal.runtime.ECMAErrors.error(ECMAErrors.java:57)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:213)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:185)
        at jdk.nashorn.internal.runtime.ECMAErrors.typeError(ECMAErrors.java:172)
        at jdk.nashorn.internal.objects.Global.checkObject(Global.java:1673)
        at jdk.nashorn.internal.objects.NativeObject.create(NativeObject.java:261)
        at jdk.nashorn.internal.scripts.Script$Recompilation$122$5673AA$\^eval\_#88\!17\^eval\_.L:1$convReturnVertxGen(vertx-js/util/utils.js:208)
        at jdk.nashorn.internal.scripts.Script$Recompilation$154$2273A$\^eval\_#88\!17\^eval\_.L:1$AuthProvider$authenticate$L:60(vertx-auth-common-js/auth_provider.js:62)
        at io.vertx.core.Handler$$NashornJavaAdapter.handle(Unknown Source)
        at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
        at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
        at io.vertx.core.impl.ContextImpl.lambda$null$13(ContextImpl.java:288)
        at io.vertx.core.impl.ContextImpl$$Lambda$12/390709726.handle(Unknown Source)
        at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:314)
        at io.vertx.core.impl.ContextImpl$$Lambda$7/1318310462.run(Unknown Source)
        at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
        at java.lang.Thread.run(Thread.java:745)
```

That was from `vertx run shirotest.js` with the following code and a shirotest.properties file containing `user.correct = pw`. It works fine if you reverse the order and include shiro_auth before router or if you use invalid credentials. Perhaps something to do with creating the User object?

``` js
var Router = require("vertx-web-js/router");
var ShiroAuth = require("vertx-auth-shiro-js/shiro_auth");
var shiroConfig = {
  "properties_path" : "file:shirotest.properties"
};
var shiro = ShiroAuth.create(vertx, 'PROPERTIES', shiroConfig);
var authInfo = {
  "username" : "correct",
  "password" : "pw"
};
shiro.authenticate(authInfo, function (res, res_err) {
  if (res_err === null) {
    logger.info("yep");
  } else {
    logger.info("nope");
  }
});
```

**Comment by pmlopes** [comment]
The issue seems to be a loop while loading the js modules. When this happens an incomplete object is loaded, however if you load the shiro impl first, then the order if fixed because the incomplete import is not used in the code and the further references get the final object.

**Comment by pmlopes** [comment]
Since this not really a auth issue but a loader issue that is known to javascript I'll close this as invalid and if needed it can reopened later on.
