### ISSUE TITLE
vertx-auth-jwt not working

### ISSUE THREAD

**Issue by mavencode01** [eclipse-vertx/vertx-auth#33]
I'm trying to integrate jwt token in my vertx but can't generate a token.

I got the exception below:

```
java.lang.RuntimeException: Algorithm not supported
    at io.vertx.ext.auth.jwt.impl.JWT.sign(JWT.java:171)
    at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.generateToken(JWTAuthProviderImpl.java:145)
    at ca.mavencode.pga.handler.AuthHandler.lambda$handle$5(AuthHandler.java:42)
    at ca.mavencode.pga.handler.AuthHandler$$Lambda$19/1795160029.handle(Unknown Source)
    at ca.mavencode.pga.jdbc.impl.JDBCAuthImpl.lambda$authenticate$1(JDBCAuthImpl.java:66)
    at ca.mavencode.pga.jdbc.impl.JDBCAuthImpl$$Lambda$20/305717969.accept(Unknown Source)
    at ca.mavencode.pga.jdbc.impl.JDBCAuthImpl.lambda$null$3(JDBCAuthImpl.java:119)
    at ca.mavencode.pga.jdbc.impl.JDBCAuthImpl$$Lambda$24/394295754.handle(Unknown Source)
    at io.vertx.core.impl.FutureImpl.checkCallHandler(FutureImpl.java:135)
    at io.vertx.core.impl.FutureImpl.setHandler(FutureImpl.java:100)
    at io.vertx.core.impl.ContextImpl.lambda$null$13(ContextImpl.java:288)
    at io.vertx.core.impl.ContextImpl$$Lambda$26/456330793.handle(Unknown Source)
    at io.vertx.core.impl.ContextImpl.lambda$wrapTask$15(ContextImpl.java:314)
    at io.vertx.core.impl.ContextImpl$$Lambda$3/1729958231.run(Unknown Source)
    at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:357)
    at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:357)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:111)
    at java.lang.Thread.run(Thread.java:745)

```

But I can see these logs on my console,

```
Sep 19, 2015 6:18:41 PM io.vertx.ext.auth.jwt.impl.JWT
INFO: HS256 not available
Sep 19, 2015 6:18:41 PM io.vertx.ext.auth.jwt.impl.JWT
INFO: HS384 not available
Sep 19, 2015 6:18:41 PM io.vertx.ext.auth.jwt.impl.JWT
INFO: HS512 not available
Sep 19, 2015 6:18:41 PM io.vertx.ext.auth.jwt.impl.JWT
INFO: RS256 not available
Sep 19, 2015 6:18:41 PM io.vertx.ext.auth.jwt.impl.JWT
INFO: RS384 not available
Sep 19, 2015 6:18:41 PM io.vertx.ext.auth.jwt.impl.JWT
INFO: RS512 not available
Sep 19, 2015 6:18:41 PM io.vertx.ext.auth.jwt.impl.JWT
INFO: ES256 not available
Sep 19, 2015 6:18:41 PM io.vertx.ext.auth.jwt.impl.JWT
INFO: ES384 not available
Sep 19, 2015 6:18:41 PM io.vertx.ext.auth.jwt.impl.JWT
INFO: ES512 not available
```

How can I resolve this and generate jwt tokens

Btw, I generated my keystore and added it to my classpath

```
keytool -genseckey -keystore keystore.jck -storetype jceks -storepass password -keyalg AES -keysize 256 -alias pga -keypass password 

```

**Comment by mavencode01** [comment]
This helped me
http://vertx.io/docs/vertx-auth-jwt/js/

Thanks,

**Comment by white-collar** [comment]
@mavencode01 , pls, can you explain me how it helped you ? I have the same problem while jwt-authorisation.

**Comment by pmlopes** [comment]
I think the issue was that the key alias used was wrong it needs to match the aliases from JWT spec so the commands to generate the keys are:

```
keytool -genseckey -keystore keystore.jceks -storetype jceks -storepass secret -keyalg HMacSHA256 -keysize 2048 -alias HS256 -keypass secret
keytool -genseckey -keystore keystore.jceks -storetype jceks -storepass secret -keyalg HMacSHA384 -keysize 2048 -alias HS384 -keypass secret
keytool -genseckey -keystore keystore.jceks -storetype jceks -storepass secret -keyalg HMacSHA512 -keysize 2048 -alias HS512 -keypass secret
keytool -genkey -keystore keystore.jceks -storetype jceks -storepass secret -keyalg RSA -keysize 2048 -alias RS256 -keypass secret -sigalg SHA256withRSA -dname "CN=,OU=,O=,L=,ST=,C=" -validity 360
keytool -genkey -keystore keystore.jceks -storetype jceks -storepass secret -keyalg RSA -keysize 2048 -alias RS384 -keypass secret -sigalg SHA384withRSA -dname "CN=,OU=,O=,L=,ST=,C=" -validity 360
keytool -genkey -keystore keystore.jceks -storetype jceks -storepass secret -keyalg RSA -keysize 2048 -alias RS512 -keypass secret -sigalg SHA512withRSA -dname "CN=,OU=,O=,L=,ST=,C=" -validity 360
keytool -genkeypair -keystore keystore.jceks -storetype jceks -storepass secret -keyalg EC -keysize 256 -alias ES256 -keypass secret -sigalg SHA256withECDSA -dname "CN=,OU=,O=,L=,ST=,C=" -validity 360
keytool -genkeypair -keystore keystore.jceks -storetype jceks -storepass secret -keyalg EC -keysize 256 -alias ES384 -keypass secret -sigalg SHA384withECDSA -dname "CN=,OU=,O=,L=,ST=,C=" -validity 360
keytool -genkeypair -keystore keystore.jceks -storetype jceks -storepass secret -keyalg EC -keysize 256 -alias ES512 -keypass secret -sigalg SHA512withECDSA -dname "CN=,OU=,O=,L=,ST=,C=" -validity 360
```

**Comment by white-collar** [comment]
Thank you, @pmlopes it works,

**Comment by white-collar** [comment]
@pmlopes pls, can you explain more details:

I have this example https://github.com/vert-x3/vertx-examples/tree/master/web-examples/src/main/java/io/vertx/example/web/jwt

I have recieved token, it's OK

Next step then I want to perform is to get protected resource. I have such browser request:

```
Accept:text/plain, */*; q=0.01
Accept-Encoding:gzip, deflate, sdch
Accept-Language:ru-RU,ru;q=0.8,en-US;q=0.6,en;q=0.4,uk;q=0.2
Authorization:Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0NzM4NjQ0MTEsImlhdCI6MTQ3Mzg2NDM1MX0=.p1AjqrQ5RhNMciRQVQpWr7IvjIh2Rmd3y0RmszgeLmY=
```

by this code:

```
$('#getProtected').on('click', function () {
            $.ajax({
                url: '/api/protected',
                dataType: 'text',
                headers: {
                    "Authorization": "Bearer " + $('#token').html().substring(15)
                },
                success: function (text) {
                    $('#protected').html(text);
                },
                error: function (err) {
                    $('#protected').html('Error: ' + err.toString());
                }
            });
        });
```

But in back I'm getting 401-error as I'm not verified.

In server I have this handler:

```
router.get("/api/protected").handler(ctx -> {
            ctx.response().putHeader("Content-Type", "text/plain");
            ctx.response().end("a secret you should keep for yourself...");
        });
```

**Comment by white-collar** [comment]
@pmlopes Sorry, I have founв solution. Last string while key generation was failed. Now all works good. Thanks.

**Comment by iLavryk** [comment]
Also if you chose algorithm which is not HS256 you should specify it directly during build JWTOptions object:
new JWTOptions().setAlgorithm("HS512").set*..()
