### ISSUE TITLE
Public / private key selection issues with JWT

### ISSUE THREAD

**Issue by jponge** [eclipse-vertx/vertx-auth#359]
I am using a `JWTAuth` instance with public / private PEM keys as follows:

```java
jwtAuth = JWTAuth.create(vertx, new JWTAuthOptions()
  .addPubSecKey(new PubSecKeyOptions()
    .setAlgorithm("RS256")
    .setBuffer(publicKey))
  .addPubSecKey(new PubSecKeyOptions()
    .setAlgorithm("RS256")
    .setBuffer(privateKey)));
```

I am issuing JWT tokens as follows:

```java
private String makeJwtToken(String username, String deviceId) {
  JsonObject claims = new JsonObject()
    .put("deviceId", deviceId);
  JWTOptions jwtOptions = new JWTOptions()
    .setAlgorithm("RS256")
    .setExpiresInMinutes(10_080) // 7 days
    .setIssuer("10k-steps-api")
    .setSubject(username);
  return jwtAuth.generateToken(claims, jwtOptions);
}
```

The code is from a service which exposes a HTTP API. Issuing tokens fails randomly with the following exception:

```
java.lang.RuntimeException: java.security.InvalidKeyException: No installed provider supports this key: (null)
	at io.vertx.ext.jwt.JWK.sign(JWK.java:617)
	at io.vertx.ext.jwt.JWT.sign(JWT.java:310)
	at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.generateToken(JWTAuthProviderImpl.java:158)
	at io.vertx.reactivex.ext.auth.jwt.JWTAuth.generateToken(JWTAuth.java:90)
	at tenksteps.publicapi.PublicApiVerticle.makeJwtToken(PublicApiVerticle.java:165)
	at tenksteps.publicapi.PublicApiVerticle.lambda$token$4(PublicApiVerticle.java:143)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:57)
	at io.reactivex.internal.operators.single.SingleMap$MapSingleObserver.onSuccess(SingleMap.java:64)
	at io.reactivex.internal.operators.single.SingleFlatMap$SingleFlatMapCallback$FlatMapSingleObserver.onSuccess(SingleFlatMap.java:111)
	at io.vertx.reactivex.impl.AsyncResultSingle.lambda$subscribeActual$0(AsyncResultSingle.java:49)
	at io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:680)
	at io.vertx.reactivex.ext.web.client.HttpRequest$10.handle(HttpRequest.java:677)
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:308)
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:295)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:270)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69)
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32)
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:267)
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:277)
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:238)
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:364)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:181)
	at io.vertx.core.impl.EventLoopContext$Duplicated.lambda$execute$0(EventLoopContext.java:84)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:510)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:518)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.InvalidKeyException: No installed provider supports this key: (null)
	at java.security.Signature$Delegate.chooseProvider(Signature.java:1138)
	at java.security.Signature$Delegate.engineInitSign(Signature.java:1179)
	at java.security.Signature.initSign(Signature.java:530)
	at io.vertx.ext.jwt.JWK.sign(JWK.java:609)
	... 29 common frames omitted
```

It seems like sometimes the public key is chosen instead of the private key.

Similarly I have a `JWTAuthHandler` in my API:

```java
JWTAuthHandler jwtHandler = JWTAuthHandler.create(jwtAuth);
```

All requests through that handler fail, it looks like the public key is not being used.

I am using the `master` branch version.
Similar code worked in Vert.x 3.8.x with https://github.com/jponge/vertx-in-action/tree/master/part2-steps-challenge/public-api

The 2 screenshots show the problems: JWT tokens are randomly issued, and tokens are never validated.

<img width="1726" alt="Screenshot 2020-01-31 at 21 39 54" src="https://user-images.githubusercontent.com/25961/73572983-7e0d9000-4472-11ea-897b-e2a380f645c5.png">

<img width="1726" alt="Screenshot 2020-01-31 at 21 41 36" src="https://user-images.githubusercontent.com/25961/73572984-7e0d9000-4472-11ea-8416-8aa89e6fc8bb.png">

**Comment by pmlopes** [comment]
@jponge CI is not working correctly but master already includes this fix.

**Comment by jponge** [comment]
I will test when snapshots are available

**Comment by jponge** [comment]
Works for me now! 🎉
