### ISSUE TITLE
Fail to decode token with GoogleAuth (and possibly GithubAuth)

### ISSUE THREAD

**Issue by hs-apotell** [eclipse-vertx/vertx-auth#380]
### Version

Version 4.0.0-milestone4, 3.8.5

### Context

When using GoogleAuth I encountered this exception -

`io.vertx.core.json.DecodeException: Failed to decode:Unrecognized token 'ɭ': was expecting ('true', 'false' or 'null')
 at [Source: (String)"ɭ�"; line: 1, column: 2]`

### Do you have a reproducer?

Discussion topic - https://groups.google.com/forum/#!topic/vertx/PHJx-ghoyuM

### Steps to reproduce

Code snippet included in the forum link above.

**Comment by pmlopes** [comment]
@hs-apotell I'm having some trouble reproducing the error. Can you please add a stack trace? I've tested with a simple google app I just created and I can see the login screen without issue on current master.

**Comment by pmlopes** [comment]
Also note that your google callback is `/` which seems a bit odd to me:

```java
OAuth2Auth googleAuthProvider = GoogleAuth.create(vertx, "CLIENT_ID", "CLIENT_SECRET", new OAuth2ClientOptions());
OAuth2AuthHandler googleOAuth2Handler = OAuth2AuthHandler.create(googleAuthProvider, "http://localhost:8080");
googleOAuth2Handler.setupCallback(router.route());
```

As the callback url is `http://localhost:8080` then the path is  `""` is that correct?

**Comment by hs-apotell** [comment]
@pmlopes The problem is after you attempt to login. The login screen shows up fine but once you provide your credentials, the callback path fails.

The callback string in `OAuth2AuthHandler` was a typo (copy/paste) error. The corrected statement in code is below.

`OAuth2AuthHandler googleOAuth2Handler = OAuth2AuthHandler.create(googleAuthProvider, "http://localhost:8080/oauth2callback");
`

Here's the call stack -
`
io.vertx.core.json.DecodeException: Failed to decode:Unrecognized token '?': was expecting ('true', 'false' or 'null')
 at [Source: (String)"??"; line: 1, column: 2]
	at io.vertx.core.json.jackson.DatabindCodec.fromParser(DatabindCodec.java:135)
	at io.vertx.core.json.jackson.DatabindCodec.fromString(DatabindCodec.java:98)
	at io.vertx.core.json.JsonObject.fromJson(JsonObject.java:842)
	at io.vertx.core.json.JsonObject.<init>(JsonObject.java:53)
	at io.vertx.ext.jwt.JWT.decode(JWT.java:194)
	at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.createAccessToken(OAuth2AuthProviderImpl.java:405)
	at io.vertx.ext.auth.oauth2.impl.OAuth2AuthProviderImpl.lambda$authenticate$2(OAuth2AuthProviderImpl.java:215)
	at io.vertx.ext.auth.oauth2.impl.OAuth2API.lambda$token$1(OAuth2API.java:219)
	at io.vertx.ext.auth.oauth2.impl.OAuth2API.lambda$null$7(OAuth2API.java:567)
	at io.vertx.core.http.impl.HttpClientResponseImpl.lambda$bodyHandler$0(HttpClientResponseImpl.java:251)
	at io.vertx.core.impl.FutureImpl.doDispatch(FutureImpl.java:127)
	at io.vertx.core.impl.FutureImpl.dispatch(FutureImpl.java:119)
	at io.vertx.core.impl.FutureImpl.tryComplete(FutureImpl.java:149)
	at io.vertx.core.http.impl.HttpClientResponseImpl$BodyHandler.handleEnd(HttpClientResponseImpl.java:277)
	at io.vertx.core.http.impl.HttpClientResponseImpl.handleEnd(HttpClientResponseImpl.java:226)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.lambda$handleBegin$3(Http1xClientConnection.java:447)
	at io.vertx.core.streams.impl.InboundBuffer.handleEvent(InboundBuffer.java:240)
	at io.vertx.core.streams.impl.InboundBuffer.write(InboundBuffer.java:130)
	at io.vertx.core.http.impl.Http1xClientConnection$StreamImpl.handleEnd(Http1xClientConnection.java:462)
	at io.vertx.core.impl.AbstractContext.emit(AbstractContext.java:183)
	at io.vertx.core.impl.EventLoopContext$Duplicated.dispatchFromIO(EventLoopContext.java:140)
	at io.vertx.core.impl.EventLoopContext.dispatch(EventLoopContext.java:74)
	at io.vertx.core.impl.EventLoopContext.access$000(EventLoopContext.java:26)
	at io.vertx.core.impl.EventLoopContext$Duplicated.dispatch(EventLoopContext.java:145)
	at io.vertx.core.http.impl.Http1xClientConnection.handleResponseEnd(Http1xClientConnection.java:670)
	at io.vertx.core.http.impl.Http1xClientConnection.handleHttpMessage(Http1xClientConnection.java:523)
	at io.vertx.core.http.impl.Http1xClientConnection.handleMessage(Http1xClientConnection.java:505)
	at io.vertx.core.net.impl.VertxHandler.channelRead(VertxHandler.java:157)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:438)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:328)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:302)
	at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:253)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1379)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1158)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1193)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:505)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:444)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:283)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:352)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1422)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:374)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:360)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:931)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:700)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:635)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:552)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:514)
	at io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.fasterxml.jackson.core.JsonParseException: Unrecognized token '?': was expecting ('true', 'false' or 'null')
 at [Source: (String)"??"; line: 1, column: 2]
	at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1798)
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:673)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._reportInvalidToken(ReaderBasedJsonParser.java:2835)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._handleOddValue(ReaderBasedJsonParser.java:1889)
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextToken(ReaderBasedJsonParser.java:747)
	at com.fasterxml.jackson.databind.ObjectMapper._initForReading(ObjectMapper.java:4129)
	at com.fasterxml.jackson.databind.ObjectMapper._readValue(ObjectMapper.java:3959)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2264)
	at io.vertx.core.json.jackson.DatabindCodec.fromParser(DatabindCodec.java:133)
	... 59 more
`

**Comment by pmlopes** [comment]
@hs-apotell I believe this issue is fixed on master, can you test it against the snapshot versions?

If you don't know how to enable snapshots, in your `~/.m2/settings.xml` (if you're on maven) add the following configuration:

```xml
<settings>
  <profiles>
    <profile>
      <id>allow-snapshots</id>
      <activation><activeByDefault>true</activeByDefault></activation>
      <repositories>
        <repository>
          <id>snapshots-repo</id>
          <url>https://oss.sonatype.org/content/repositories/snapshots</url>
          <releases><enabled>false</enabled></releases>
          <snapshots><enabled>true</enabled></snapshots>
        </repository>
      </repositories>
   </profile>
  </profiles>
</settings>
```

After this use the versions `4.0.0-SNAPSHOT` for all vert.x components.

From what I can tell on my test app, this doesn't happen anymore as the code you're referring from the stacktrace is already deprecated and not used (plus many fixes have been pushed after the milestone 4 release).

**Comment by pmlopes** [comment]
I'm closing this issue as it is assumed to be fixed and there is not interaction for a long time.
