### ISSUE TITLE
Base64 decoding error for JWKS 

### ISSUE THREAD

**Issue by ashiishsharma** [eclipse-vertx/vertx-auth#479]
### Questions

Base64 decoding error for JWKS 

### Version

vertx-auth-common-4.0.3

### Context

```
java.lang.IllegalArgumentException: Illegal base64 character 5f
	at java.util.Base64$Decoder.decode0(Base64.java:714) ~[na:1.8.0_222]
	at java.util.Base64$Decoder.decode(Base64.java:526) ~[na:1.8.0_222]
	at java.util.Base64$Decoder.decode(Base64.java:549) ~[na:1.8.0_222]
	at io.vertx.core.json.JsonObject.getBinary(JsonObject.java:258) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.ext.auth.impl.jose.JWK.createEC(JWK.java:570) ~[vertx-auth-common-4.0.3.jar:4.0.3]
	at io.vertx.ext.auth.impl.jose.JWK.<init>(JWK.java:449) ~[vertx-auth-common-4.0.3.jar:4.0.3]
	at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.<init>(JWTAuthProviderImpl.java:109) ~[vertx-auth-jwt-4.0.3.jar:4.0.3]
	at io.vertx.ext.auth.jwt.JWTAuth.create(JWTAuth.java:42) ~[vertx-auth-jwt-4.0.3.jar:4.0.3]
	at xxxxx.lambda$getJWTAuth$5(xxx.java:373) ~[xxx-2.0.0.jar:na]
	at xxxxx.lambda$getJWTAuth3$7(xxx.java:446) ~[xxx-2.0.0.jar:na]
	at io.vertx.ext.web.client.impl.HttpContext.handleDispatchResponse(HttpContext.java:285) ~[vertx-web-client-3.7.1.jar:3.7.1]
	at io.vertx.ext.web.client.impl.HttpContext.execute(HttpContext.java:272) ~[vertx-web-client-3.7.1.jar:3.7.1]
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:250) ~[vertx-web-client-3.7.1.jar:3.7.1]
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:69) ~[vertx-web-client-3.7.1.jar:3.7.1]
	at io.vertx.ext.web.client.impl.predicate.PredicateInterceptor.handle(PredicateInterceptor.java:32) ~[vertx-web-client-3.7.1.jar:3.7.1]
	at io.vertx.ext.web.client.impl.HttpContext.next(HttpContext.java:247) ~[vertx-web-client-3.7.1.jar:3.7.1]
	at io.vertx.ext.web.client.impl.HttpContext.fire(HttpContext.java:257) ~[vertx-web-client-3.7.1.jar:3.7.1]
	at io.vertx.ext.web.client.impl.HttpContext.dispatchResponse(HttpContext.java:218) ~[vertx-web-client-3.7.1.jar:3.7.1]
	at io.vertx.ext.web.client.impl.HttpContext.lambda$null$2(HttpContext.java:341) ~[vertx-web-client-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:320) ~[vertx-core-3.7.1.jar:3.7.1]
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38) [vertx-core-3.7.1.jar:3.7.1]
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:495) ~[netty-transport-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:905) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.34.Final.jar:4.1.34.Final]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_222]

```

### Steps to reproduce

        WebClient client = WebClient.create(vertx, new WebClientOptions().setSsl(true));
        client.get(443, jwksUri.getHost(), jwksUri.getPath()).timeout(EXTERNAL_REQUEST_TIMEOUT)
                .as(BodyCodec.jsonObject())
                .send(webRequest -> {
                    if (!webRequest.succeeded()) {
                        log.info("*****************************************************");
                        log.info(String.format("Could not fetch JWKS from URI: %s", jwksUriString));
                        log.info("*****************************************************");
                    }
                    HttpResponse<JsonObject> response = webRequest.result();
                    String responseString = new String(Base64.getDecoder().decode(Base64.getEncoder().
                            encode(response.body().toString().getBytes())));
                    JsonObject jwksResponse = new JsonObject(responseString);
                    JsonArray keys = jwksResponse.getJsonArray("keys");

                    // Configure JWT validation options
                    JWTOptions jwtOptions = new JWTOptions();
                    jwtOptions.setIssuer(issuer);
                    // extract JWKS from keys array
                    List jwks = ((List<Object>) keys.getList()).stream()
                            .map(o -> new JsonObject((Map<String, Object>) o))
                            .collect(Collectors.toList());

                    log.info("*****************************************************");
                    log.info("jwks : " + jwks);
                    log.info("*****************************************************");

                    // configure JWTAuth
                    JWTAuthOptions jwtAuthOptions = new JWTAuthOptions();
                    jwtAuthOptions.setJwks(jwks);
                    jwtAuthOptions.setJWTOptions(jwtOptions);
                    jwtAuthOptions.setPermissionsClaimKey("realm_access/roles");

                    this.jwtAuth = JWTAuth.create(vertx, jwtAuthOptions);

**Comment by pmlopes** [comment]
@ashiishsharma I've created a reproducer and there is nothing wrong in 4.0.3 or the latest 4.1.0.Beta1. I do see a problem in your dependencies though:

<pre>
java.lang.IllegalArgumentException: Illegal base64 character 5f
	at java.util.Base64$Decoder.decode0(Base64.java:714) ~[na:1.8.0_222]
	at java.util.Base64$Decoder.decode(Base64.java:526) ~[na:1.8.0_222]
	at java.util.Base64$Decoder.decode(Base64.java:549) ~[na:1.8.0_222]
	at io.vertx.core.json.JsonObject.getBinary(JsonObject.java:258) ~[<b>vertx-core-3.7.1.jar:3.7.1</b>]
	at io.vertx.ext.auth.impl.jose.JWK.createEC(JWK.java:570) ~[<b>vertx-auth-common-4.0.3.jar:4.0.3</b>]
	at io.vertx.ext.auth.impl.jose.JWK.<init>(JWK.java:449) ~[vertx-auth-common-4.0.3.jar:4.0.3]
	at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.<init>(JWTAuthProviderImpl.java:109) ~[vertx-auth-jwt-4.0.3.jar:4.0.3]
	at io.vertx.ext.auth.jwt.JWTAuth.create(JWTAuth.java:42) ~[vertx-auth-jwt-4.0.3.jar:4.0.3]
</pre>

You have vert.x core 3.7.1 and vertx-auth 4.0.3 in your runtime. This is the root cause of the exception because before vert.x 4.0.0 the `getBinary()` method was not following the IJSON spec and using the wrong format.

On a side note you can avoid a few lines of code in your example:

```java
String responseString = new String(Base64.getDecoder().decode(Base64.getEncoder().
                        encode(response.body().toString().getBytes())));
JsonObject jwksResponse = new JsonObject(responseString);
JsonArray keys = jwksResponse.getJsonArray("keys");
```

Is the same as:

```java
JsonArray keys = response.body().getJsonArray("keys");
```

And you showed me we should create an overload to `setJWKs()` accepting a `JsonArray` but meanwhile you can also replace:

```java
// extract JWKS from keys array
List jwks = ((List<Object>) keys.getList()).stream()
        .map(o -> new JsonObject((Map<String, Object>) o))
        .collect(Collectors.toList());

// configure JWTAuth
JWTAuthOptions jwtAuthOptions = new JWTAuthOptions();
jwtAuthOptions.setJwks(jwks);
```

With:

```java
// configure JWTAuth
JWTAuthOptions jwtAuthOptions = new JWTAuthOptions();
jwtAuthOptions.setJwks((List<JsonObject>) keys.getList());
```

**Comment by ashiishsharma** [comment]
Thanks for the prompt response, let me try it out and reply back.

**Comment by ashiishsharma** [comment]
Solution worked for me.
Thanks.
