### ISSUE TITLE
JWT algorithm typo?

### ISSUE THREAD

**Issue by ckaminski** [eclipse-vertx/vertx-auth#49]
java.lang.RuntimeException: Algorithm not supported
        at io.vertx.ext.auth.jwt.impl.JWT.sign(JWT.java:180)
        at io.vertx.ext.auth.jwt.impl.JWTAuthProviderImpl.generateToken(JWTAuthProviderImpl.java:145)
        at io.vertx.groovy.ext.auth.jwt.JWTAuth.generateToken(JWTAuth.groovy:55)
        at io.vertx.groovy.ext.auth.jwt.JWTAuth$generateToken$0.call(Unknown Source)

https://github.com/vert-x3/vertx-auth/blob/master/vertx-auth-jwt/src/main/java/io/vertx/ext/auth/jwt/impl/JWT.java

public String sign(JsonObject payload, JsonObject options) {
final String algorithm = options.getString("algorithm", "HS256"); <<-- Supposed to be RS256?

**Comment by ckaminski** [comment]
Ok, appears to not be a typo, I have some other issue at work here.
Sorry for the confusion.

**Comment by ckaminski** [comment]
Did not have a matching key algorithm in my keystore.  PEBKAC.  Sorry for the trouble.
