### ISSUE TITLE
NullPointerException in private Constructor of OAuth2AuthHandlerImpl

### ISSUE THREAD

**Issue by fbuetler** [eclipse-vertx/vertx-auth#606]
### Version

I encountered the issue with vertx-auth-oauth2 4.3.7 but also with the latest master commit.

### Context

I encountered a `NullPointerException` while using the following code snippet:

```
final OAuth2AuthHandler authHandler = OAuth2AuthHandler.create(vertx, authProvider, callbackURL)
        .setupCallback(callback)
        .extraParams(responseModeParam)
        .withScope(sessionScope);
```
The `withScope` call [triggers the creation](https://github.com/vert-x3/vertx-web/blob/4.3.7/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java#L244) of a new `OAuth2AuthHandlerImpl` with a private constructor.
Note, that some extraParams are set beforehand.
In the private constructor the [extraParams are copied](https://github.com/vert-x3/vertx-web/blob/4.3.7/vertx-web/src/main/java/io/vertx/ext/web/handler/impl/OAuth2AuthHandlerImpl.java#L111), but obviously trigger a `NullPointerException`:

```
// state copy
    if (base.extraParams != null) {
      extraParams = extraParams.copy();
    }
```

Start of the stack trace:
```
20:03:39.348 [vert.x-eventloop-thread-0] ERROR io.vertx.core.impl.ContextBase - Unhandled exception
java.lang.NullPointerException: null
        at io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl.<init>(OAuth2AuthHandlerImpl.java:111)
        at io.vertx.ext.web.handler.impl.OAuth2AuthHandlerImpl.withScope(OAuth2AuthHandlerImpl.java:244)
```

### Proposed Fix

```
// state copy
    if (base.extraParams != null) {
      extraParams = base.extraParams.copy();
    }
```

### Mitigation

Put the `extraParams()` at the end such that the path triggering the Exception in the private constructor is not used.

**Comment by fbuetler** [comment]
My bad, wrong repo. Moved to [vertx-web](https://github.com/vert-x3/vertx-web/issues/2336)
